// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC4ydRQcg3Fc7JzzWiSntizx82A8XKJcg',
    appId: '1:172822741233:web:a9cb826d5a24e8a923e950',
    messagingSenderId: '172822741233',
    projectId: 'genshin-app-sanber',
    authDomain: 'genshin-app-sanber.firebaseapp.com',
    storageBucket: 'genshin-app-sanber.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATMnJR__U02wvgaDio4lKmY1tH18xVDjc',
    appId: '1:172822741233:android:8ca4517781968fb023e950',
    messagingSenderId: '172822741233',
    projectId: 'genshin-app-sanber',
    storageBucket: 'genshin-app-sanber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD__yqrEY2BfM2diYERYKbC-7qo4Pb4ak',
    appId: '1:172822741233:ios:bf75deee71744f5623e950',
    messagingSenderId: '172822741233',
    projectId: 'genshin-app-sanber',
    storageBucket: 'genshin-app-sanber.appspot.com',
    iosClientId:
        '172822741233-dbu8oba6rf0hepb96dqrt3vh9en1s5nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.genshinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD__yqrEY2BfM2diYERYKbC-7qo4Pb4ak',
    appId: '1:172822741233:ios:bf75deee71744f5623e950',
    messagingSenderId: '172822741233',
    projectId: 'genshin-app-sanber',
    storageBucket: 'genshin-app-sanber.appspot.com',
    iosClientId:
        '172822741233-dbu8oba6rf0hepb96dqrt3vh9en1s5nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.genshinApp',
  );
}
